version: '3.8'
services:
  postgres:
    image: postgres:alpine
    container_name: biblioteca_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - biblioteca_network

volumes:
  postgres_data:

networks:
  biblioteca_network:
    driver: bridge
